spring:
  application:
    name: Lab1
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5434/lab_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
jwt:
  secret: 'My5ecr3tT0k3N^[a-zA-Z0-9._]^+$MyR@nd0m5tr1ng25ecur3MyT0k3ns0D0ntCr@ck1t'
server:
  error:
    include-message: always