services:

  postgres:
    container_name: postgres-lab
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres: